# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161003_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archives',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Archives', verbose_name='档案日期'),
        ),
        migrations.AlterField(
            model_name='archives',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='archives',
            name='name',
            field=models.CharField(max_length=20, verbose_name='档案日期'),
        ),
    ]
