# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161003_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
